[LOGGING]
log_file = process.log

[SETTINGS]
csv_file = entities.csv
output_xlsx = Results.xlsx
api_delay = 1.0
max_retries = 3
# NUOVO PARAMETRO: indica quanti "Cache Miss" elaborare al massimo prima di fermarsi
max_scan_files = 5
